version: '3'
services:
  portfolio:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.local
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env.local